### ISSUE TITLE
Extending the language

### ISSUE THREAD

**Issue by Kongduino** [slviajero/tinybasic#13]
I got a bit lost between the tokens and the negative numeric values... Do you have a tutorial explaining how to extend the language?

Thanks

(BTW, I managed to compile and run tinybasic with only a few changes on nRF52840)

**Comment by slviajero** [comment]
https://github.com/slviajero/tinybasic/wiki/How-to-compile-Stefan's-BASIC-(and-how-it-works)#how-to-add-your-own-commands

**Comment by slviajero** [comment]
Tutorial added to documentation.

**Comment by slviajero** [comment]
It is complicated. ;-) Arduino PROGMEM logic makes it a bit clumsy. I have written a few words at the end of this text right now: 
https://github.com/slviajero/tinybasic/wiki/How-to-compile-Stefan's-BASIC-(and-how-it-works) <https://github.com/slviajero/tinybasic/wiki/How-to-compile-Stefan's-BASIC-(and-how-it-works)>
Have a look and please tell me if this works for you. I can write more on specific topics if needed.
