### ISSUE TITLE
TAB reversal - documentation note

### ISSUE THREAD

**Issue by EncomLab** [slviajero/tinybasic#18]
This is a long standing issue with BASIC syntax. The Apple and "Standard BASIC" TAB use PRINT in opposite relationship:
The Apple TAB = TAB 20 : PRINT "Hello World!" 
The ECMA and ANSI TAB = PRINT TAB(10); "Hello World!" 

I would not change the implementation as you have it as it is correct for the Apple 1 version of BASIC, but it may be worth documenting.

**Comment by slviajero** [comment]
Thank you! TAB is a strange animal. In Apple Integer BASIC it simply ejects n spaces and is a statement. In MS BASIC it is a function in PRINT which is really weird from the point of view of grammar. Also, it seems to be a tabulator function, so PRINT „Hello“; TAB(20); „World“ prints World at position 20. I will write a note in the documentation.

**Comment by slviajero** [comment]
Corrected in the two documentation pages.
