### ISSUE TITLE
backspace can go before start of input

### ISSUE THREAD

**Issue by henk1955** [slviajero/tinybasic#37]
i changed this in hardware-arduino.h lines 3547 ...
} else if ( (c == 127 || c == 8) && z.a>1) {
	z.a--;
} else {
	b[z.a++]=c;
} 

to

} else if (c == 127 || c == 8){
        if( z.a>1) {
     			z.a--;
        }
} else {
	b[z.a++]=c;
}

**Comment by slviajero** [comment]
oh yes, this seems to be a good idea

**Comment by slviajero** [comment]
fixed and tested, thank you, will make this part of the main code
