### ISSUE TITLE
Floating point overflow

### ISSUE THREAD

**Issue by RonLinu** [slviajero/tinybasic#38]
Hello Stefan!
I guess you probably know about this but here it is: TinyBASIC locks up when handling a number bigger than 1e38.
    print 1e39
    x = 1e39
will lock up the interpreter.
I admit this does not occur often, mostly because of a programming error.

On the other hand, underflow is handled correctly as it returns 'zero' which is ok.

Tested on an Arduino Mega 2560

**Comment by slviajero** [comment]
will look into this soon. i rewrote the number code anyway
