### ISSUE TITLE
ARDUINO_TTGO_T7_V14_Mini32 definition

### ISSUE THREAD

**Issue by souphead** [slviajero/tinybasic#59]
ARDUINO_TTGO_T7_V14_Mini32 is used a few times in runtime.ccp but it doesn't seem to be defined anywhere. Causes problems with the definitions of vgawrite() and soundGenerator() .

**Comment by slviajero** [comment]
will check this soon, actually I didnt test the vga code, still too busy with the other platforms. Sent from my iPhoneOn Oct 17, 2023, at 3:02 AM, souphead ***@***.***> wrote:﻿
ARDUINO_TTGO_T7_V14_Mini32 is used a few times in runtime.ccp but it doesn't seem to be defined anywhere. Causes problems with the definitions of vgawrite() and soundGenerator() .

**Comment by slviajero** [comment]
Fixed now, wrong runtime.h prototypes and dependency handling. Compiles now but not tested on hardware.

**Comment by slviajero** [comment]
Should be fixed now-

**Comment by souphead** [comment]
Yes compiles and seems to run OK. I have a few other questions but I'll ask them in a separate issue.
