### ISSUE TITLE
Running code from micro sd cards?

### ISSUE THREAD

**Issue by vrdriver** [slviajero/tinybasic#61]
Hi, I love this concept of running basic on an Arduino.
Is there presently any way of loading programs that are stored on an sd card and running them that way?
Have I misread the concept of this project, or does it all have to by typed in?
Sorry to be a bother
Steve.

**Comment by slviajero** [comment]
sure! in hardware.h set the ARDUINOSD macro. only good if you have enough memory. most boards like the nano every, mega, r4 are ok.Sent from my iPhoneOn Dec 10, 2023, at 4:50 AM, Steve ***@***.***> wrote:﻿
Hi, I love this concept of running basic on an Arduino.
Is there presently any way of loading programs that are stored on an sd card and running them that way?
Have I misread the concept of this project, or does it all have to by typed in?
Sorry to be a bother
Steve.

**Comment by vrdriver** [comment]
Hey thanks! I'll take a look at it. I have a UNO and a MEGA, so maybe I'll be able to get things running on the MEGA.

**Comment by slviajero** [comment]
Yes! There are a few tricks. If you run in trouble, tell me. 
Some SD cards have odd timing problems.

**Comment by slviajero** [comment]
Closed, already implemented.
