### ISSUE TITLE
Motor encoders and interrupts 

### ISSUE THREAD

**Issue by EncomLab** [slviajero/tinybasic#63]
Hi Stefan - sorry for being away from this project for far too long!  I have a question regarding the use of HC-020K optical encoders for motor control - namely the best way to use interrupts and/or the best commands to allow for the counting of pulses from them.  I have attempted using the EVENT command but it appears I am getting a pulse length and not a count of pulses.  Best regards and I look forward as always to your feedback! - Brian

**Comment by slviajero** [comment]
Hi Brian,

the EVENT command is tricky and not really well tested. What exactly are you trying to do with it. 
Do you have some code you tried? 

In general, EVENT is used to react to one event by jumping to a subroutine. There one has to count the 
number of interrupts. Is this what you are trying to do?

Best Regards,
Stefan
