### ISSUE TITLE
Autorun from SD?

### ISSUE THREAD

**Issue by EncomLab** [slviajero/tinybasic#68]
The autorun from EEPROM is great - but I'm running out of room lol.  https://github.com/BleuLlama/TinyBasicPlus has a SDcard autorun function that works similar to your autorun EEPROM  except it auto loads and runs the program saved to SD as autorun.bas.  Could we have a function like this?

**Comment by slviajero** [comment]
Already exists ;-).
Create a file named autoexec.bas in the top level of the SD card. This should run on start.
