### ISSUE TITLE
Move docs to seperate repo

### ISSUE THREAD

**Issue by coolcoder613eb** [slviajero/tinybasic#71]
The docs take up most of the download/clone size.
It may be best to move the docs to a separate repo, amending the history as well.

**Comment by slviajero** [comment]
Good point, I will check and separate this. Has indeed grown too much.Sent from my iPadOn Dec 10, 2024, at 7:21 AM, coolcoder613eb ***@***.***> wrote:﻿
The docs take up most of the download/clone size.
It may be best to move the docs to a separate repo, amending the history as well.

**Comment by slviajero** [comment]
Reduced documents to the essentials.

**Comment by coolcoder613eb** [comment]
Have you removed it from the history, or should people just clone with `--depth`?

**Comment by slviajero** [comment]
Should be fully removed (git rm). Hope this worked.
