### ISSUE TITLE
Memory error when running on TTGO VGA32

### ISSUE THREAD

**Issue by coolcoder613eb** [slviajero/tinybasic#72]
I get a memory error whenever I assign a variable.

**Comment by slviajero** [comment]
Which hardware.h and runtime.h settings do you use?Sent from my iPadOn Dec 10, 2024, at 9:59 AM, coolcoder613eb ***@***.***> wrote:﻿
I get a memory error whenever I assign a variable.

**Comment by slviajero** [comment]
MQTT seems to be broken. I need to look into this. Do you use it or does the error appear also without it?

**Comment by coolcoder613eb** [comment]
I am not using it.

**Comment by slviajero** [comment]
Which libraries do you use? Are they identical? I ran my usual test programs and they all were ok. 
Did you use the release code or the actual code in the repo right now? I tested against the actual code. 
If there is a bug in the release I will create a new release prestissomo.

**Comment by slviajero** [comment]
the important ones are ESP32 core 2.0.7FabGL 1.0.9background info, the error you see (memory error on variable assignment) means heap corruption. this happens when the C stack memory overflows and poisons the BASIC memory.  on a esp32 this is very strange. if it is the repo code it could mean that my own dev tree is not in sync with the repo, i will double check this tonight Sent from my iPhoneOn Dec 12, 2024, at 11:17 PM, coolcoder613eb ***@***.***> wrote:﻿
Repo code, and could you list all the libraries you use so i can find the versions?

**Comment by coolcoder613eb** [comment]
I tried changing esp32 from 2.0.17 to 2.0.7, no difference.

**Comment by slviajero** [comment]
I cross checked now the repo. The code is exactly the one I use on my development system. 
It compiles and runs correctly. Could it be that you accidentially made any other change? Anything that uses memory? 
Did you check FabGL. Ist it the newest one? 1.0.9?

Try to set MEMSIZE directly to cross check. You could try a 

#define MEMSIZE 8192

to radically reduce to 8k. 

I saw that you renamed some commands. This should be completely harmless. But maybe during editing you changed something?

**Comment by slviajero** [comment]
PS: is this what you see after compile: 
Sketch uses 596897 bytes (45%) of program storage space. Maximum is 1310720 bytes.
Global variables use 30516 bytes (9%) of dynamic memory, leaving 297164 bytes for local variables. Maximum is 327680 bytes.

**Comment by coolcoder613eb** [comment]
This is what I see:
Sketch uses 594729 bytes (45%) of program storage space. Maximum is 
1310720 bytes.
Global variables use 30644 bytes (9%) of dynamic memory, leaving 297036 
bytes for local variables. Maximum is 327680 bytes.
Memsize 8k doesn't help.

**Comment by slviajero** [comment]
Does language.h specify#define BASICFULLif not, try this.Sent from my iPhoneOn Dec 15, 2024, at 2:21 AM, coolcoder613eb ***@***.***> wrote:﻿
This is what I see:
Sketch uses 594729 bytes (45%) of program storage space. Maximum is 
1310720 bytes.
Global variables use 30644 bytes (9%) of dynamic memory, leaving 297036 
bytes for local variables. Maximum is 327680 bytes.
Memsize 8k doesn't help.

**Comment by coolcoder613eb** [comment]
It does.

**Comment by slviajero** [comment]
This is indeed very odd. Could you please run the program 

10 ERROR  GOTO 35
20 DUMP HIMEM -20
25 SET 0,4
30 A=10
35 SET 0,0
40 DUMP HIMEM -20
50 PRINT USR(0,9),USR(0,13),USR(0,32)

for me?

**Comment by coolcoder613eb** [comment]
![DSCN1086](https://github.com/user-attachments/assets/88848150-8e79-4065-8a07-0f799f83a1ef)

**Comment by slviajero** [comment]
Now it is clear where this comes from. You have set 

/* experimental features, don't use unless you know the code */
/* 
 * this setting uses the EEPROM as program storage 
 * The idea is to create a virtual memory layout starting from 0 with the EEPROM
 * from elength() and then adding the BASIC RAM to it. himem and top need to be 
 * handled carefully. 
 */
#define ARDUINOPGMEEPROM

which is not good on an ESP. It makes the EEPROM the core program memory which only works on the AVR. 
Unfortunately I have checked this in without any safeguard. Will correct this immediately. 

Please recompile with

#undef ARDUINOPGMEEPROM

**Comment by coolcoder613eb** [comment]
It works!
